---
title: "Project RSI_Immune: tSNE Figure"
shorttitle: "RSI_Immune"
project: 
srpt_number: 
version: "`r CosmosReportTemplates::git_tag()`"
author: 'Steven Eschrich'
date: "`r format(Sys.time(), '%d %B, %Y')`"
investigators:
  - name: "Daniel Grass"
  - name: "Javier Torres-Roca"
project_team:
analysis_team:
analysis_contact:
organization: 
output:
  CosmosReportTemplates::bbsr_pdf: default
  word_document: default
  pdf_document: default
  html_document: default
toc: yes
---

```{r setup}
library(readxl)
library(dplyr)
library(ggplot2)
library(grid)
```

```{r load}

graph_styles<-read_excel("../../data.raw/Graph_Colors_Shapes.xlsx")

ts.100<-readRDS("tsne-perplexity=100-clusters.RDS")
result.table<-readRDS("../../data.derived/tcc-primary-metadata.RDS")

# Combine metadata with tSNE results for clustering.
df<-data.frame(x.100=ts.100$Y[rownames(result.table),1],
                y.100=ts.100$Y[rownames(result.table),2],
                result.table,
                stringsAsFactors = FALSE,
                check.names=FALSE)


# Four samples have NA's for the tissue abbreviation/SOO_Merged field.
df<-df[which(!is.na(df$SOO_Merged)),]


saveRDS(df,file="tsne-dataframe-for-clustering.RDS")
```



The function defined below graphs the tSNE data, with abbreviations.
```{r}
tcc.tsne.ggplot<-function(df, type,main="") {
  # Merge label into data
  graph_data<-as_tibble(df) %>% 
    left_join(select(graph_styles, c("SOO_Merged","tissue_abbreviations")), by=c("SOO_Merged"="SOO_Merged"))
  
  tcc.plot<-ggplot(graph_data,aes(x=x.100,y=y.100,
                          label=tissue_abbreviations,
                          shape=tissue_abbreviations)) 
  
  
  # Setting this name means the legend is coalesced.
  tcc.plot<-tcc.plot + 
    aes(col=tissue_abbreviations) +
    scale_colour_manual(values = structure(graph_styles$tsne_color,
                                           names=graph_styles$tissue_abbreviations), 
                        name="Tumor Type")  +
    guides(fill=guide_legend(nrow=4),
           shape=guide_legend(nrow=4),
           colour=guide_legend(nrow=4)) 
  
  
  tcc.plot<- tcc.plot +
    ggtitle(main) +
    
    
    # Turn off x and y labels; remove gray background; remove tick marks, etc.
    #xlab("")+
    #ylab("")+
    theme_bw() +
    theme(
      # Turn off a lot of decoration on the plot
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.title = element_blank(),
      title = element_blank(),
      legend.text = element_text(size=8),
      legend.position="bottom",
      legend.margin = margin(t=0,r=0,b=0,l=0,unit="pt"),
      legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
       #legend.box.spacing = unit(1,unit="pt"),
       
       legend.spacing=unit(0,units="pt"),
       # Carve out space for the legend at the top
       plot.margin=unit(c(t=1,r=1,b=1,l=1),"mm"),
       # Position the legend in the top left corner (assuming a 1x1 grid I think)
       #legend.position=c(.4,1.05),
   
      
    ) +
    
    
    # Plot the points, with a smaller size since there are so many.  
    #geom_point(size=1.5)+
    geom_point(size=1) +
    # Manually set the colors for the points to hard-code the information. It is colored by  Site of Origin.
    
    # Setting this name means the legend is coalesced.
    scale_shape_manual(values = structure(
      graph_styles$shape,
      names=graph_styles$tissue_abbreviations),
      name="Tumor Type",
      guide=ifelse(type=="main","legend","none")
      
    ) 
    
    
    # Annotate the clusters with specific tissue-oriented labels. This is hard-coded with coordinates based on 
    # the initial cluster plot. Changing the clusters changes these!
    text_annotation<-graph_styles %>%
      filter(tsne_plot_label==TRUE) %>%
      mutate(label=coalesce(tsne_label, tissue_abbreviations))

    tcc.plot<-tcc.plot +
      annotate("text",
             x=text_annotation$tsne_x,
             y=text_annotation$tsne_y,
             col=text_annotation$tsne_color,
             label=text_annotation$label
      )
  
  
  
  return(tcc.plot)
}


```


Generate the figure.
```{r}
cairo_pdf(file="Figure_1_tSNE_Clustering.pdf",width=7,height=5)
#grid.newpage()
#pushViewport(viewport(layout = grid.layout(nrow = 2, ncol = 1, heights = unit(c(0.9,0.1),"null"))))
#pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1))
print(tcc.tsne.ggplot(df,"main",main=""))#,newpage=FALSE)
#upViewport()

#grid.text(x=unit(1,"in"),
#          y=unit(0.3,"in"),
#          "Extended Data Figure 1"
#)

dev.off()

```

