---
title: "Project RSI_Immune: Estimate Algorithm"
shorttitle: "RSI_Immune"
project: 
srpt_number: 
version: "`r CosmosReportTemplates::git_tag()`"
author: 'Steven Eschrich'
date: "`r format(Sys.time(), '%d %B, %Y')`"
investigators:
  - name: "Daniel Grass"
  - name: "Javier Torres-Roca"
project_team:
analysis_team:
analysis_contact:
organization: 
output:
  CosmosReportTemplates::bbsr_article_pdf: default
  word_document: default
  pdf_document: default
  html_document: default
toc: yes
---

```{r setup}

```

```{r}
source("create_tcc_metadata.R")
metadata<-create_tcc_metadata()

source("load_gene_expression.R")
x<-load_gene_expression()
x<-x[,rownames(metadata)]

```


A short sanity check of results:
```{r}
# How do things look?
table(metadata$SOO_Conformed,metadata$SOO_SubCategory)
```

```{r}
saveRDS(x,file="../../data.derived/tcc-primary-expression.RDS")
saveRDS(metadata,file="../../data.derived/tcc-primary-metadata.RDS")
```

```{r session.info.table,results='asis',echo=FALSE}
CosmosReportTemplates::print_session_information()
```
