---
title: "Project RSI_Immune: iRIS Violin Plot"
shorttitle: "RSI_Immune"
project: 
srpt_number: 
version: "`r CosmosReportTemplates::git_tag()`"
author: 'Steven Eschrich'
date: "`r format(Sys.time(), '%d %B, %Y')`"
investigators:
  - name: "Daniel Grass"
  - name: "Javier Torres-Roca"
project_team:
analysis_team:
analysis_contact:
organization: 
output:
  CosmosReportTemplates::bbsr_pdf: default
  word_document: default
  pdf_document: default
  html_document: default
toc: yes
---

```{r setup}
library(readxl)
library(grid)
```


```{r}
result.table<-readRDS("../../data.derived/result_table_with_iRIS.RDS")
graph_details<-read_excel("../../data.raw/Graph_Colors_Shapes.xlsx")
graph_map<-graph_details$tissue_abbreviations
names(graph_map)<-graph_details$SOO_Merged
```



Figure : Violin plot of iris score

```{r}
source("../../src/dviolin_plot.R")
cairo_pdf("Figure_3D_iris_violin_plot.pdf",height=11,width=8.5)
pushViewport(viewport(layout=grid.layout(3, 1,
                                         heights=unit(c(1, 1, 1), c("lines", "null", "lines")))))
pushViewport(viewport(layout.pos.row=2,layout.pos.col=1))
dviolin_plot(data.frame(category=graph_map[result.table$SOO_Merged],values=result.table$iRIS),
             plot_vertical = FALSE,bw="nrd0",
             ylab="", value_label="iRIS",
             density.color.high=heat.colors(3)[1],
             density.color.mid=heat.colors(3)[2],
             density.color.low=heat.colors(6)[4],
             max.colors=100,
             grand_median_line=TRUE, cex=1, show_main=FALSE,
             show_n=TRUE,n_prefix="")
popViewport()
pushViewport(viewport(layout.pos.row=3,layout.pos.col=1))
#grid.text(0.2,0.8, label="Extended Data Figure 4")#, gp=gpar(fontface="bold"))
popViewport()
dev.off()

# For later,
# as.ggplot(~dviolin_plot())).
#
```


